apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g3gfx78o2-python 
  janus-idp.io/tekton: g3gfx78o2-python
  backstage.io/kubernetes-id: g3gfx78o2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g3gfx78o2-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml